apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zmal1r8j1-java-springboot
  janus-idp.io/tekton: zmal1r8j1-java-springboot
  backstage.io/kubernetes-id: zmal1r8j1-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zmal1r8j1-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
